# Generated by Django 4.2.2 on 2023-06-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_alter_boardmodel_good_alter_boardmodel_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='good',
            field=models.IntegerField(),
        ),
    ]
